//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace CURELab.SignLanguage.RecognitionSystem
{
    public class Classifier
    {

        private LeariningModel _learningModel;

        public LeariningModel m_learningModel
        {
            get { return _learningModel; }
            set { _learningModel = value; }
        }
        public Classifier()
        {

        }



    } 
}


