//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CURELab.SignLanguage.HandDetector
{
    public class DataTransferEventArgs : EventArgs
    {
        public Object m_data;

        public DataTransferEventArgs(Object data)
        {
            m_data = data;
        }
    }

    
}