//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CURELab.SignLanguage.HandDetector.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CURELab.SignLanguage.HandDetector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Connect a device first! 的本地化字符串。
        /// </summary>
        internal static string ConnectDeviceFirst {
            get {
                return ResourceManager.GetString("ConnectDeviceFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kinect connected using Kinect SDK 的本地化字符串。
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kinect connected using via OpenNI 的本地化字符串。
        /// </summary>
        internal static string ConnectedOpenNI {
            get {
                return ResourceManager.GetString("ConnectedOpenNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Kinect Ready 的本地化字符串。
        /// </summary>
        internal static string NoKinectReady {
            get {
                return ResourceManager.GetString("NoKinectReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Oni file connected 的本地化字符串。
        /// </summary>
        internal static string ONIFile {
            get {
                return ResourceManager.GetString("ONIFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to write screenshot to 的本地化字符串。
        /// </summary>
        internal static string ScreenshotWriteFailed {
            get {
                return ResourceManager.GetString("ScreenshotWriteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Screenshot saved to 的本地化字符串。
        /// </summary>
        internal static string ScreenshotWriteSuccess {
            get {
                return ResourceManager.GetString("ScreenshotWriteSuccess", resourceCulture);
            }
        }
    }
}
