//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class DataTransferEventArgs : EventArgs
{
    public int m_data;
    public int m_startFrame;
    public int m_endFrame;
    
    public DataTransferEventArgs(int data)
    {
        m_data = data;
    }
}

