//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Diagnostics;
using System.Runtime.InteropServices;

public class LearningController
{

    private Classifier _classifier;

    public Classifier m_classifier
    {
        get {  return _classifier; }      
    }
    

    private Postprocessor _postprocessor;
    /// <summary>
    /// data receiver
    /// </summary>
    public Postprocessor m_postprocessor
    {
        get { return _postprocessor; }
    }

    public LearningController()
    {
        _classifier = new Classifier();
        _postprocessor = new Postprocessor();
        ConsoleManager.Show();

    }

    public void Begin()
    {
        m_classifier.Begin();
    }

}


