//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class VisualFeatureModule 
{
    protected Classifier m_classifier;
    protected DataWarehouse m_dataWarehouse;
    public VisualFeatureModule() { }
    public VisualFeatureModule(Classifier classifier)
    {
        m_classifier = classifier;
        m_dataWarehouse = classifier.m_dataProcessor.m_dataWarehouse;
    }

    public virtual void OnDataTransfer(Object sender, DataTransferEventArgs args)
    {
        Console.WriteLine("visual callback:" + args.m_data);
    }


}

