//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class VisualFeatureModule : ISubject
{
    protected Classifier m_classifier;
    protected DataWarehouse m_dataWarehouse;
    public VisualFeatureModule() { }
    public VisualFeatureModule(Classifier classifier)
    {
        m_classifier = classifier;
        m_dataWarehouse = classifier.m_dataProcessor.m_dataWarehouse;
    }
    public void BeginTest()
    {
        for (int i = 0; i < 10; i++)
        {
            Console.WriteLine("visual test:" + i);
            if (i == 8)
            {
                NofityAll(new DataTransferEventArgs(i));
            }
        }
    }

    public virtual void OnDataTransfer(Object sender, DataTransferEventArgs args)
    {
        Console.WriteLine("visual callback:" + args.m_data);
    }

    public event DataTransferEventHandler m_dataTransferEvent;

    public void NofityAll(DataTransferEventArgs e)
    {
        if (m_dataTransferEvent != null)
        {
            m_dataTransferEvent(this, e);
        }
        else
        {
            Console.WriteLine("no boundler from visual");
        }
    }

}

